---
# This role installs ZSH and makes it the default shell for users

- name: Install ZSH
  package: name=zsh state=present
  become: "{{ 'no' if ansible_os_family == 'Darwin' else 'yes' }}"

- name: Install Git (required for oh-my-zsh)
  package: name=git state=present
  become: "{{ 'no' if ansible_os_family == 'Darwin' else 'yes' }}"

- name: Install curl (required for oh-my-zsh)
  package: name=curl state=present
  become: "{{ 'no' if ansible_os_family == 'Darwin' else 'yes' }}"

- name: Install util-linux-user
  package: name=util-linux-user state=present
  when: ansible_distribution == "Amazon"
  become: yes

- name: Install zshrc
  copy:
    src: zshrc
    dest: ~{{ansible_user}}/.zshrc
    owner: "{{ansible_user}}"
  become: yes

- name: Install zshenv
  copy:
    src: zshenv
    dest: ~{{ansible_user}}/.zshenv
    owner: "{{ansible_user}}"
  become: yes

- name: Install zprofile
  copy:
    src: zprofile
    dest: ~{{ansible_user}}/.zprofile
    owner: "{{ansible_user}}"
  become: yes

- name: Set ZSH as login shell and install oh-my-zsh for current set of users
  script: files/set-zsh-shell.sh "{{ansible_user}}"
  become: yes
