# According to zsh man page, the following files are read during startup, in this order:
#
# /etc/zshenv
# ~/.zshenv
# /etc/zprofile  [login shell only]
# ~/.zprofile    [login shell only]
# /etc/zshrc     [interactive shell only]
# ~/.zshrc       [interactive shell only]
# /etc/zlogin    [login shell only]
# ~/.zlogin      [login shell only]
#
# As the OSX /etc/zprofile processes the PATH variable, we must do our PATH processing here, after OSX.

function path() { echo $PATH | tr : '\n' }
function path_head() { [ -d $1 ] && PATH=$1:$PATH }
function path_tail() { [ -d $1 ] && PATH=$PATH:$1 }

[ -r ${HOME}/.zprofile.local ] && source ${HOME}/.zprofile.local

path_head $HOME/bin

export PATH
