# According to zsh man page, the following files are read during startup, in this order:
#
# /etc/zshenv
# ~/.zshenv
# /etc/zprofile  [login shell only]
# ~/.zprofile    [login shell only]
# /etc/zshrc     [interactive shell only]
# ~/.zshrc       [interactive shell only]
# /etc/zlogin    [login shell only]
# ~/.zlogin      [login shell only]
#
# As the OSX /etc/zprofile processes the PATH variable, we must do our PATH processing here, after OSX.

function path() { echo $PATH | tr : '\n' }
function path_head() { [ -d $1 ] && PATH=$1:$PATH }
function path_tail() { [ -d $1 ] && PATH=$PATH:$1 }

[ -r ${HOME}/.zprofile.local ] && source ${HOME}/.zprofile.local

path_head $HOME/bin
path_head "$( python -m site --user-base )/bin"

# Dedupe entries in PATH
if [ -n "$PATH" ]; then
  old_PATH=$PATH:; PATH=
  while [ -n "$old_PATH" ]; do
    x=${old_PATH%%:*}       # the first remaining entry
    case $PATH: in
      *:"$x":*) ;;          # already there
      *) PATH=$PATH:$x;;    # not there yet
    esac
    old_PATH=${old_PATH#*:}
  done
  PATH=${PATH#:}
  unset old_PATH x
fi

export PATH
