# According to zsh man page, the following files are read during startup, in this order:
#
# /etc/zshenv
# ~/.zshenv
# /etc/zprofile  [login shell only]
# ~/.zprofile    [login shell only]
# /etc/zshrc     [interactive shell only]
# ~/.zshrc       [interactive shell only]
# /etc/zlogin    [login shell only]
# ~/.zlogin      [login shell only]
#
