# According to zsh man page, the following files are read during startup, in this order:
#
# /etc/zshenv
# ~/.zshenv
# /etc/zprofile  [login shell only]
# ~/.zprofile    [login shell only]
# /etc/zshrc     [interactive shell only]
# ~/.zshrc       [interactive shell only]
# /etc/zlogin    [login shell only]
# ~/.zlogin      [login shell only]
#
# Note that the OSX /etc/zprofile processes the PATH variable. That may affect the PATH after this file has processed it.

# Path
function path() { echo $PATH | tr : '\n' }
function path_head() { [ -d $1 ] && PATH=$1:$PATH }
function path_tail() { [ -d $1 ] && PATH=$PATH:$1 }

[ -r ${HOME}/.zprofile.local ] && source ${HOME}/.zprofile.local

test -d "${HOME}/.linuxbrew" && lbhome="${HOME}/.linuxbrew" ||
  test -d "/home/linuxbrew/.linuxbrew" && lbhome="/home/linuxbrew/.linuxbrew" ||
  lbhome=""
if [ ! -z "${lbhome}" ]; then
  eval $("${lbhome}/bin/brew" shellenv)
  path_head "${lbhome}/opt/python/libexec/bin"
fi

path_head "$( python -m site --user-base )/bin"
path_head $HOME/bin

# Dedupe entries in PATH
if [ -n "$PATH" ]; then
  old_PATH=$PATH:; PATH=
  while [ -n "$old_PATH" ]; do
    x=${old_PATH%%:*}       # the first remaining entry
    case $PATH: in
      *:"$x":*) ;;          # already there
      *) PATH=$PATH:$x;;    # not there yet
    esac
    old_PATH=${old_PATH#*:}
  done
  PATH=${PATH#:}
  unset old_PATH x
fi

export PATH

if [ -z "${JAVA_HOME}" ]; then
  if which update-alternatives >/dev/null; then
    export JAVA_HOME="$( dirname "$( dirname "$( update-alternatives --query javac | grep '^Value: ' | cut -d' ' -f2 )")")"
  fi
fi
if [ -z "${JAVA_HOME}" ]; then
  export JAVA_HOME="$( dirname "$( dirname "$( which javac )")")"
fi

# Maven
# export MAVEN_OPTS="-Xmx512m -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M"

# GnuPG
export GPG_TTY="$(tty)"

# Local settings
[ -r ${HOME}/.zshenv.local ] && source ${HOME}/.zshenv.local
